language: python

# you can use Python 3.7 instead
python: "3.8"

# don't clone more than necessary
git:
  depth: 1


env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

install:
  - pip install coverage
  - pip install django
  - pip install django-heroku
  - pip install gunicorn
  - pip install selenium
  - python manage.py collectstatic
# script to run tests. Script can have many commands, one per line.
script: 
  - coverage run --source='.' manage.py test
after_script:
  - bash <(curl -s https://codecov.io/bash)