language: python

# you can use Python 3.7 instead
python: "3.8"

# don't clone more than necessary
git:
  depth: 1

dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - pip install coverage
  - pip install django
  - pip install django-heroku
  - pip install gunicorn
  - pip install selenium
# script to run tests. Script can have many commands, one per line.
script: 
  - coverage run --source='.' manage.py test
  - python manage.py collectstatic
after_script:
  - bash <(curl -s https://codecov.io/bash)