# Generated by Django 3.1.2 on 2020-10-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive', models.CharField(max_length=200)),
                ('image_passive', models.CharField(max_length=200)),
                ('skill_q', models.CharField(max_length=200)),
                ('image_q', models.CharField(max_length=200)),
                ('skill_w', models.CharField(max_length=200)),
                ('image_w', models.CharField(max_length=200)),
                ('skill_e', models.CharField(max_length=200)),
                ('image_e', models.CharField(max_length=200)),
                ('skill_r', models.CharField(max_length=200)),
                ('image_r', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noxusProject.spell')),
            ],
        ),
    ]
