# Generated by Django 3.1.2 on 2020-11-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageChampion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default=None, max_length=200, null=True)),
                ('splash_art', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSpell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive', models.CharField(default=None, max_length=200)),
                ('q', models.CharField(default=None, max_length=200)),
                ('w', models.CharField(default=None, max_length=200)),
                ('e', models.CharField(default=None, max_length=200)),
                ('r', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default=None, max_length=200)),
                ('img', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passive', models.CharField(default=None, max_length=200)),
                ('q', models.CharField(default=None, max_length=200)),
                ('w', models.CharField(default=None, max_length=200)),
                ('e', models.CharField(default=None, max_length=200)),
                ('r', models.CharField(default=None, max_length=200)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noxusProject.imagespell')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(default=None, max_length=200, null=True)),
                ('img', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='noxusProject.imagechampion')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noxusProject.spell')),
            ],
        ),
    ]
