# Generated by Django 3.1.2 on 2020-11-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChampion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('starter1', models.IntegerField(default=0)),
                ('starter2', models.IntegerField(default=0)),
                ('items_1', models.IntegerField(default=0)),
                ('items_2', models.IntegerField(default=0)),
                ('items_3', models.IntegerField(default=0)),
                ('items_4', models.IntegerField(default=0)),
                ('items_5', models.IntegerField(default=0)),
                ('items_6', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Rune',
        ),
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
