# Generated by Django 3.1.2 on 2020-11-13 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noxusProject', '0002_auto_20201108_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune', models.CharField(default=None, max_length=200, null=True)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('img', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('img', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubRune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune', models.CharField(default=None, max_length=200, null=True)),
                ('row', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('img', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemchampion',
            name='items_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='noxusProject.items'),
        ),
        migrations.AlterField(
            model_name='itemchampion',
            name='items_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='noxusProject.items'),
        ),
        migrations.AlterField(
            model_name='itemchampion',
            name='items_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item3', to='noxusProject.items'),
        ),
        migrations.AlterField(
            model_name='itemchampion',
            name='items_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item4', to='noxusProject.items'),
        ),
        migrations.AlterField(
            model_name='itemchampion',
            name='items_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item5', to='noxusProject.items'),
        ),
        migrations.AlterField(
            model_name='itemchampion',
            name='items_6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item6', to='noxusProject.items'),
        ),
        migrations.AlterField(
            model_name='itemchampion',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itemchampion',
            name='starter1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter1', to='noxusProject.items'),
        ),
        migrations.AlterField(
            model_name='itemchampion',
            name='starter2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter2', to='noxusProject.items'),
        ),
        migrations.CreateModel(
            name='RuneChampion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('key_stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='noxusProject.keystone')),
                ('row1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row1', to='noxusProject.subrune')),
                ('row2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row2', to='noxusProject.subrune')),
                ('row3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row3', to='noxusProject.subrune')),
                ('rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to='noxusProject.rune')),
                ('sub_row1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_row1', to='noxusProject.subrune')),
                ('sub_row2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_row2', to='noxusProject.subrune')),
                ('sub_rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='noxusProject.rune')),
            ],
        ),
    ]
