# Generated by Django 3.1 on 2020-11-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noxusProject', '0002_auto_20201108_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='adc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='champion',
            name='jungler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='champion',
            name='mid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='champion',
            name='support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='champion',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
