# Generated by Django 3.1 on 2020-11-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noxusProject', '0004_imagesummonnerspell_summonnerspell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesummonnerspell',
            old_name='image',
            new_name='img',
        ),
    ]
