# Generated by Django 3.1.2 on 2020-11-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noxusProject', '0005_auto_20201112_2117'),
        ('noxusProject', '0003_auto_20201113_0914'),
    ]

    operations = [
    ]
